### ISSUE TITLE
Progress 2 - Membuat analisis biaya terhadap perangkat yg digunakan

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#10]
Buatlah analisis pembiayaan pada perangkat yg dipilih seperti spesifikasi/kualitas pada komponen, harga komponen, ketahanan komponen dan lainnya

**Comment by ciiraiin** [comment]
[RAB Final Project (Kelompok 7).xlsx](https://github.com/FayezRizqi/projekakhir-smartdetector-kel7/files/11543588/RAB.Final.Project.Kelompok.7.xlsx)

**Comment by ciiraiin** [comment]
[RAB Final Project (Kelompok 7).xlsx](https://github.com/FayezRizqi/projekakhir-smartdetector-kel7/files/11543972/RAB.Final.Project.Kelompok.7.xlsx)

**Comment by ciiraiin** [comment]
[Penggunaan Hardware.docx](https://github.com/FayezRizqi/projekakhir-smartdetector-kel7/files/11543990/Penggunaan.Hardware.docx)
