### ISSUE TITLE
Progress 3 - Membuat Firmware Design Telegram

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#13]
Buat rancangan firmware Notifikasi di Telegram

**Comment by MuhammadRShihab22** [comment]
[https://lucid.app/lucidchart/7d0a6def-1516-4c5f-9137-3ee2e847cc98/edit?viewport_loc=-270%2C63%2C1953%2C883%2C0_0&invitationId=inv_c7fa18a0-32c7-41aa-b210-2337ebb0f1ea](url)

**Comment by MuhammadRShihab22** [comment]
https://lucid.app/lucidchart/0ebf348d-9b7b-4d12-b0e9-efcb507e22d8/edit?viewport_loc=-79%2C91%2C2474%2C1119%2C0_0&invitationId=inv_5215afd1-6536-4c38-aece-b952d00656b3
