### ISSUE TITLE
Progress 3 - Membuat Wireframe Design BLYNK

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#14]
buat rancangan Wireframe pada BLYNK

**Comment by Alviiiin06** [comment]
![Uploading WhatsApp Image 2023-05-30 at 17.19.23
![Screenshot (234)](https://github.com/FayezRizqi/projekakhir-smartdetector-kel7/assets/129011899/b3e7637b-9fee-489b-b24b-9b88e53cbdc8)
.jpeg…]()
![Screenshot (235)](https://github.com/FayezRizqi/projekakhir-smartdetector-kel7/assets/129011899/10211cdd-06e0-46e9-abb8-17e9ea4f5fa4)

**Comment by Alviiiin06** [comment]
![WhatsApp Image 2023-05-30 at 17 19 23](https://github.com/FayezRizqi/projekakhir-smartdetector-kel7/assets/129011899/059923c6-fe39-43de-99a0-81624b251a37)

**Comment by Alviiiin06** [comment]
![Uploading Screenshot (234).png…]()
