### ISSUE TITLE
progress 4 - Membuat Program koneksi ke BLYNK

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#18]
Buat coding untuk mengkoneksikan Data ke BLYNK

**Comment by Alviiiin06** [comment]
#define BLYNK_TEMPLATE_ID "TMPL6OQfbW0NZ"
#define BLYNK_TEMPLATE_NAME "Project Akhir"
#define BLYNK_AUTH_TOKEN "1_ElaSLGM-gWhpxlJqA_OU9cgH9FjE_N"
