### ISSUE TITLE
Progres 1 - Membuat Batasan Masalah

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#3]
buat batasan masalah

**Comment by Alviiiin06** [comment]
1. Projek ini memiliki batasan dalam hal area cakupan. Sensor asap dan gas memiliki jarak deteksi tertentu, yang berarti mereka hanya dapat mendeteksi keberadaan asap dan gas di area yang terjangkau oleh sensor tersebut. Oleh karena itu, proyek ini akan lebih efektif jika diterapkan dalam skala yang terbatas, misalnya dalam satu ruangan, zona tertentu di luar ruangan, atau area yang lebih kecil.
2. Projek ini dapat didesain untuk mendeteksi jenis asap dan gas tertentu yang telah ditentukan sebelumnya. Sensor-sensor yang digunakan akan dioptimalkan untuk mendeteksi jenis-jenis asap dan gas yang telah diidentifikasi. Namun, mungkin ada jenis asap atau gas tertentu yang tidak dapat dideteksi oleh sensor yang digunakan dalam proyek ini.
3. Lingkungan sekitar, seperti suhu ekstrem, kelembaban tinggi, atau kondisi cuaca yang buruk, dapat mempengaruhi kinerja sensor dan peralatan lainnya dalam sistem. Diperlukan perhatian khusus untuk memastikan bahwa peralatan yang digunakan tahan terhadap kondisi tersebut atau diberikan perlindungan tambahan untuk memastikan kinerja yang konsisten.
