### ISSUE TITLE
Progress 2 - Membuat Platform IoT apa yang dipakai

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#6]
buatlah platform Iot yang dipakai pada projek

**Comment by Alviiiin06** [comment]
Blynk adalah platform Internet of Things (IoT) yang dirancang untuk memfasilitasi pengembangan prototipe dan aplikasi IoT. Blynk menyediakan perangkat lunak dan layanan cloud yang memungkinkan pengguna mengontrol dan memantau perangkat elektronik dari smartphone mereka.
Dengan Blynk, pengguna dapat membuat aplikasi seluler yang terhubung ke berbagai perangkat seperti Arduino, Raspberry Pi, ESP8266, dan lainnya. Platform ini memungkinkan pengguna membuat antarmuka pengguna khusus untuk mengontrol perangkat mereka, seperti tombol, penggeser, grafik, dan tampilan lainnya
