### ISSUE TITLE
Progress 2 - Membuat Fitur apa saja oleh solusi projek

### ISSUE THREAD

**Issue by FayezRizqi** [FayezRizqi/projekakhir-smartdetector-kel7#7]
buat fitur apa saja yang oleh dari solusi projek

**Comment by MuhammadRShihab22** [comment]
Fitur :

1. Monitoring sensor

Monitoring sensor adalah fitur untuk memonitor kondisi sensor-sensor yang terpasang, seperti sensor asap, sensor gas berbahaya, sensor suhu, sensor kelembaban, dan lainnya. Data dari sensor-sensor ini dapat ditampilkan secara real-time dalam bentuk grafik atau angka.

2. Notifikasi

Fitur Notifikasi memberikan peringatan kepada pengguna melalui aplikasi Blynk atau pesan teks jika terdeteksi adanya kebakaran atau keberadaan gas berbahaya. Hal ini memungkinkan pengguna untuk merespons dan mengambil tindakan secepat mungkin.

3. Sistem kontrol

Sistem kontrol adalah fitur untuk mengontrol sistem yang tersedia seperti mengaktifkan sprinkler atau mematikan listrik di area sekitar yang mengalami gangguan atau terdampak. Pengguna dapat mengakses kontrol ini melalui aplikasi Blynk untuk merespons kejadian dengan cepat.

4. Log data dan analisis

Log data sensor dan Analisis adalah fitur dimana Seluruh kegiatan yang terjadi disimpan dan data ini dapat dianalisis untuk memahami tren, pola, atau kondisi yang memerlukan perhatian khusus. Hal ini juga memungkinkan pengguna untuk membuat laporan atau mengambil keputusan berdasarkan data historis.

5. Interface costum

Solusi ini memungkinkan pengguna untuk membuat user interface kustom di aplikasi Blynk. Pengguna dapat menyesuaikan tata letak, widget, dan tampilan sesuai dengan preferensi atau kebutuhan mereka.
